import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Geist, Space_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mobile Artificial Intelligence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </head>
      <body className={`${geistSans.variable} ${spaceMono.variable}`}>
        <header>
            <div id='logo-group'>
                <Link href="/">
                  <Image src="/favicon.svg" alt="logo" width={40} height={40} />
                </Link>
                <h1>
                  <span id="title-full">Mobile Artificial Intelligence</span>
                  <span id="title-short">Mobile AI</span>
                </h1>
            </div>
            <div id='link-group'>
                <a href="https://github.com/orgs/Mobile-Artificial-Intelligence/repositories">Github</a>
                <Link href="/privacy">Privacy Policy</Link>
            </div>
        </header>
        {children}
      </body>
    </html>
  );
}
